version: '3'

services:

  eventDB:
    container_name: EventDB
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: eventDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    ports:
      - 5432:5432

  keycloakDB:
    container_name: AuthDB
    image: mysql:8.0.27
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306

  keycloak:
    container_name: Auth
    image: quay.io/keycloak/keycloak:15.0.2
    restart: always
    volumes:
    - ./keycloak-import:/opt/jboss/keycloak/imports
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: MYSQL
      DB_ADDR: keycloakDB
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
    ports:
      - 8180:8080
    command: 
      - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/keycloak-realm.json"
    depends_on:
      - "keycloakDB"